/* ScombZ Utilities */
/* exportCalender.js */
function exportCalender() {
    if(location.href.includes("https://scombz.shibaura-it.ac.jp/lms/timetable")){
        const ttbody = document.getElementById("selectTimetable");
        if(ttbody){
            ttbody.insertAdjacentHTML("afterBegin",`
            <style>
                .utilities-calender-export-btn{
                    display:block;
                }
            </style>
            <a href="javascript:void(0);" class="utilities-calender-export-btn" id="utlCalExportBtn">Googleカレンダー形式にエクスポート</a>
            `);
            document.getElementById("utlCalExportBtn").addEventListener("click",function(){
                /** デバッグ用↓ **/
                const gcal2022 = {
                    "termLength":[
                        {
                            "name":"1Q",
                            "begin":"2022/4/11",
                            "end":"2022/6/4"
                        },
                        {
                            "name":"2Q",
                            "begin":"2022/6/6",
                            "end":"2022/7/25"
                        },
                        {
                            "name":"3Q",
                            "begin":"2022/9/24",
                            "end":"2022/11/18"
                        },
                        {
                            "name":"4Q",
                            "begin":"2022/11/21",
                            "end":"2023/1/23"
                        }
                    ],
                    "holidays":[
                        {
                            "name":"昭和の日",
                            "description":"",
                            "date":"2022/4/29"
                        },
                        {
                            "name":"憲法記念日",
                            "description":"",
                            "date":"2022/5/3"
                        },
                        {
                            "name":"みどりの日",
                            "description":"",
                            "date":"2022/5/4"
                        },
                        {
                            "name":"こどもの日",
                            "description":"",
                            "date":"2022/5/5"
                        },
                        {
                            "name":"文化の日",
                            "description":"",
                            "date":"2022/11/3"
                        },
                        {
                            "name":"成人の日",
                            "description":"",
                            "date":"2023/1/9"
                        },
                        {
                            "name":"休講",
                            "description":"授業回数調整",
                            "date":"2022/5/2"
                        },
                        {
                            "name":"休講",
                            "description":"大宮祭準備",
                            "date":"2022/5/21"
                        },
                        {
                            "name":"休講",
                            "description":"芝浦祭準備",
                            "date":"2022/11/2"
                        },
                        {
                            "name":"休講",
                            "description":"芝浦祭準備",
                            "date":"2022/11/5"
                        },
                        {
                            "name":"休講",
                            "description":"芝浦祭片付け",
                            "date":"2022/11/7"
                        },
                        {
                            "name":"休講",
                            "description":"授業回数調整",
                            "date":"2022/11/8"
                        },
                        {
                            "name":"休講",
                            "description":"大学院入試",
                            "date":"2022/11/19"
                        },
                        {
                            "name":"休講",
                            "description":"大学入試共通テスト",
                            "date":"2023/1/14"
                        }
                    ],
                    "longholidays":[
                        {
                            "name":"冬休み",
                            "description":"",
                            "begin":"2022/12/26",
                            "end":"2023/1/6"
                        }
                    ],
                    "specialDays":[
                        {
                            "name":"学生大会",
                            "description":"",
                            "date":"2022/6/27",
                            "cansel":[3,4,5,6,7]
                        },
                        {
                            "name":"大宮祭",
                            "description":"",
                            "date":"2022/5/21"
                        },
                        {
                            "name":"海の日(通常授業)",
                            "description":"※授業実施",
                            "date":"2022/7/18"
                        },
                        {
                            "name":"TOEIC試験日",
                            "description":"該当者のみ",
                            "date":"2022/7/26"
                        },
                        {
                            "name":"入学式",
                            "description":"",
                            "date":"2022/4/2"
                        },
                        {
                            "name":"秋季学位授与式",
                            "description":"",
                            "date":"2022/9/22"
                        },
                        {
                            "name":"秋季入学式",
                            "description":"",
                            "date":"2022/9/22"
                        },
                        {
                            "name":"スポーツの日(通常授業)",
                            "description":"※授業実施",
                            "date":"2022/10/10"
                        },
                        {
                            "name":"芝浦祭",
                            "description":"",
                            "date":"2022/11/4"
                        },
                        {
                            "name":"芝浦祭",
                            "description":"",
                            "date":"2022/11/5"
                        },
                        {
                            "name":"芝浦祭",
                            "description":"",
                            "date":"2022/11/6"
                        },
                        {
                            "name":"TOEIC試験日",
                            "description":"",
                            "date":"2023/1/24"
                        },
                        {
                            "name":"学位授与式",
                            "description":"",
                            "date":"2023/3/22"
                        }
                    ]
                };
                /** デバッグ用↑ **/
                chrome.storage.local.get({
                    timetableData : null
                },function(items){
                    if(items.timetableData === null){
                        window.alert("ERROR:時間割の読み込みに失敗しました。");
                    }else{
                        let cal = ics();
                        const $timetableDatas = JSON.parse(decodeURIComponent(items.timetableData));
                        for(const $timetableData of $timetableDatas){
                            if($timetableData.day && $timetableData.time && 
                                $timetableData.day > 0 &&
                                $timetableData.time > 0){//正しい週ごとの時間割形式だったら
                                    //ここを編集↓
                                    const gcal = gcal2022;
                                        for(let i=0; gcal.holidays[i]; i++){
                                            cal.addEvent(gcal.holidays[i].name, gcal.holidays[i].description, '', gcal.holidays[i].date, gcal.holidays[i].date);
                                        }
                                        for(let i=0; gcal.specialDays[i]; i++){
                                            cal.addEvent(gcal.holidays[i].name, gcal.holidays[i].description, '', gcal.holidays[i].date, gcal.holidays[i].date);
                                        }
                                    break;
                                    //ここを編集↑
                                }
                        }
                        cal.download('2022学年歴');
                    }
                });
            });
        }
    }
}